config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :metrics
  resources :user_roles
  resources :roles
  devise_for :users
  resources :users
  resources :registers
  resources :reviews, only: %i[index create update]

  resources :questions do
    resources :answers
  end

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  post 'click', to: 'metrics#click'

  resources :metrics, only: %i[create index]

  get '*path' => redirect('/')

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_role.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: user_roles
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  role_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_user_roles_on_role_id  (role_id)
#  index_user_roles_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (role_id => roles.id)
#  fk_rails_...  (user_id => users.id)
#
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role

  # validates :role_id , presence:true
  # validates :user_id , presence:true
  # the combination of role_id and user_id should be always unique
  validates :role_id, uniqueness: { scope: :user_id }
end

app/controllers/user_roles_controller.rb
# frozen_string_literal: true

class UserRolesController < ApplicationController
  load_and_authorize_resource
  before_action :set_user_role, only: %i[show edit update destroy]

  # GET /user_roles
  def index
    @user_roles = UserRole.all
  end

  # GET /user_roles/1
  def show; end

  # GET /user_roles/new
  def new
    @user_role = UserRole.new
  end

  # GET /user_roles/1/edit
  def edit; end

  # POST /user_roles
  def create
    @user_role = UserRole.new(user_role_params)

    if @user_role.save
      redirect_to @user_role, notice: 'User role was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /user_roles/1
  def update
    if @user_role.update(user_role_params)
      redirect_to @user_role, notice: 'User role was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_roles/1
  def destroy
    @user_role.destroy
    redirect_to user_roles_url, notice: 'User role was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_role
    @user_role = UserRole.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_role_params
    params.require(:user_role).permit(:user_id, :role_id)
  end
end

app/views/user_roles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user_role) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :user
    = f.association :role

  .form-actions
    = f.button :submit

app/views/user_roles/edit.html.haml
%h1 Editing user_role

= render 'form'

= link_to 'Show', @user_role
\|
= link_to 'Back', user_roles_path

app/views/user_roles/index.html.haml
%h1 Listing user_roles

%table
  %thead
    %tr
      %th User
      %th Role
      %th
      %th
      %th

  %tbody
    - @user_roles.each do |user_role|
      %tr
        %td= user_role.user
        %td= user_role.role
        %td= link_to 'Show', user_role
        %td= link_to 'Edit', edit_user_role_path(user_role)
        %td= link_to 'Destroy', user_role, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User role', new_user_role_path

app/views/user_roles/new.html.haml
%h1 New user_role

= render 'form'

= link_to 'Back', user_roles_path

app/views/user_roles/show.html.haml
%p#notice= notice

%p
  %b User:
  = @user_role.user
%p
  %b Role:
  = @user_role.role

= link_to 'Edit', edit_user_role_path(@user_role)
\|
= link_to 'Back', user_roles_path