config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :metrics
  resources :user_roles
  resources :roles
  devise_for :users
  resources :users
  resources :registers
  resources :reviews, only: %i[index create update]

  resources :questions do
    resources :answers
  end

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  post 'click', to: 'metrics#click'

  resources :metrics, only: %i[create index]

  get '*path' => redirect('/')

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: answers
#
#  id          :bigint           not null, primary key
#  answer      :string
#  likes       :integer
#  rating      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :bigint           not null
#
# Indexes
#
#  index_answers_on_question_id  (question_id)
#
# Foreign Keys
#
#  fk_rails_...  (question_id => questions.id)
#
class Answer < ApplicationRecord
  belongs_to :question
  validates :answer, presence: true
  validates :likes, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :get_question
  before_action :set_answer, only: %i[show edit update destroy]

  # GET /answers
  def index
    @answers = @question.answer
  end

  # GET /answers/1
  def show; end

  # GET /answers/new
  def new
    @answer = @question.build_answer
  end

  # GET /answers/1/edit
  def edit; end

  # POST /answers
  def create
    @answer = @question.build_answer(answer_params)
    @answer.likes = 0
    @answer.rating = 0
    respond_to do |format|
      if @answer.save
        format.html { redirect_to question_path(@question), notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to question_answer_path(@question), notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answer_path(@question), notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_answer
    @answer = @question.answer
  end

  # Only allow a list of trusted parameters through.
  def answer_params
    params.require(:answer).permit(:answer, :rating, :likes, :question_id)
  end

  # rubocop:disable Naming/AccessorMethodName
  def get_question
    @question = Question.find(params[:question_id])
  end
  # rubocop:enable Naming/AccessorMethodName
end

app/views/answers/_form.html.haml
= simple_form_for([@question, @answer], local: true) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .row.mb-4
      = f.input :answer, label: false, :as => :text, placeholder: "Add the Answer", :input_html => { :rows => 7 , :style => 'width: 100%; resize: none;'}

  .container
    .row
      .col.text-center
        .form-actions
          = f.button :submit, class: "btn btn-outline-primary"

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answers
\|
= link_to 'Back', question_answers_path

app/views/answers/index.html.haml
.container
  %h1 Listing answer
  .row.justify-content-center.p-0.mt-4
    .col-12
      .table-responsive
        %table.table.table-striped.align-middle
          %thead.table-dark.align-middle
            %tr
              %th.text-center.px-4{:scope => "col"} Answer
              %th.text-center.px-4{:scope => "col"} Rating
              %th.text-center.px-4{:scope => "col"} Likes
              %th.text-center.px-4{:scope => "col"} Question
              %th.text-center.px-4{:scope => "col"} Delete Answer?
          %tbody
            %tr.text-start
              %td.text-center.px-4= @answers.answer
              %td.text-center.px-4= @answers.rating
              %td.text-center.px-4= @answers.likes
              %td.text-center.px-4= @answers.question.question
              %td.text-center.px-4= link_to 'Destroy', question_answers_path, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', questions_path

app/views/answers/show.html.haml
#notice.alert.alert-success{:role => "alert" }
  =notice

%p
  %b Answer:
  = @answer.answer
%p
  %b Rating:
  = @answer.rating
%p
  %b Likes:
  = @answer.likes
%p
  %b Question:
  = @answer.question

= link_to 'Edit', edit_question_answer_path(@answer)
\|
= link_to 'Back', questions_path