config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :metrics
  resources :user_roles
  resources :roles
  devise_for :users
  resources :users
  resources :registers
  resources :reviews, only: %i[index create update]

  resources :questions do
    resources :answers
  end

  match '/403', to: 'errors#error_403', via: :all
  match '/404', to: 'errors#error_404', via: :all
  match '/422', to: 'errors#error_422', via: :all
  match '/500', to: 'errors#error_500', via: :all

  get :ie_warning, to: 'errors#ie_warning'
  post 'click', to: 'metrics#click'

  resources :metrics, only: %i[create index]

  get '*path' => redirect('/')

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/role.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: roles
#
#  id         :bigint           not null, primary key
#  role_type  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Role < ApplicationRecord
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles

  validates :role_type, uniqueness: true, presence: true
  validates :role_type, uniqueness: { case_sensitive: false }
  enum role_type: { normal: 0, admin: 1, product_owner: 2, reporter: 3 }
end

app/controllers/roles_controller.rb
# frozen_string_literal: true

class RolesController < ApplicationController
  load_and_authorize_resource
  before_action :set_role, only: %i[show edit update destroy]

  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/1
  def show; end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit; end

  # POST /roles
  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to @role, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /roles/1
  def update
    if @role.update(role_params)
      redirect_to @role, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /roles/1
  def destroy
    @role.destroy
    redirect_to roles_url, notice: 'Role was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def role_params
    params.require(:role).permit(:role_type)
  end
end

app/views/roles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@role) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :role_type

  .form-actions
    = f.button :submit

app/views/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h1 Listing roles

%table
  %thead
    %tr
      %th Role type
      %th
      %th
      %th

  %tbody
    - @roles.each do |role|
      %tr
        %td= role.role_type
        %td= link_to 'Show', role
        %td= link_to 'Edit', edit_role_path(role)
        %td= link_to 'Destroy', role, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Role', new_role_path

app/views/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.haml
%p#notice= notice

%p
  %b Role type:
  = @role.role_type

= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path